CREATE TABLE IF NOT EXISTS `autofarm_rewards` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` INT UNSIGNED NOT NULL,
  `char_id` INT UNSIGNED NOT NULL,
  `nameid` INT UNSIGNED NOT NULL,
  `amount` INT NOT NULL DEFAULT 1,
  `identify` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `refine` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `attribute` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `card0` INT UNSIGNED NOT NULL DEFAULT 0,
  `card1` INT UNSIGNED NOT NULL DEFAULT 0,
  `card2` INT UNSIGNED NOT NULL DEFAULT 0,
  `card3` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_autofarm_rewards_owner` (`account_id`,`char_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
