// Custom Season / Rate Engine
//--------------------------------------------------------------
// Enable the per-character season/rate system.
// Rates are selected by the Season Manager NPC.
customrate_enable: on
